---
baseurl: ca-fundraising-tester.pages.dev
permalink: pretty
title: CA Fundraising
google_analytics_id: ''
homepage:
  show_call_box: true
logo:
  mobile: images/logo/LogoMakr-5Xd7PR.png
  desktop: images/logo/LogoMakr-4v4hrB.png
  desktop_height: 36px
footer:
  copyright_text: Created by CA NPO
seo:
  meta_og_title: 'CA Fundraising'
  meta_og_type: website
  meta_og_url: https://ca-fundraising-tester.pages.dev
  meta_og_image: https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png
  meta_og_description: Concorida Academy nonprofit organization helps parents and students to pay tuition and other expenses through concessions work at stadiums.
  meta_twitter_card: 'summary'
  meta_twitter_site: ''
  meta_twitter_creator: ''
collections:
  services:
    output: true
  team:
    output: true
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
- jekyll-environment-variables
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE.md
- LICENSE
- README.md
url: ''
